version: '3.8'

# Create postgres service
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_NAME}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_db: