"""Added description to tags

Revision ID: 1ae86736882e
Revises: d09939a35a3b
Create Date: 2022-05-04 04:35:38.070421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae86736882e'
down_revision = 'd09939a35a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'description')
    # ### end Alembic commands ###
