"""Updated tag

Revision ID: c5afacf143b8
Revises: 87252032dd58
Create Date: 2022-05-03 14:14:01.436038

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "c5afacf143b8"
down_revision = "87252032dd58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tags", ["slug"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="unique")

    # ### end Alembic commands ###
